name: e_commerce
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  get: ^4.6.1
  dio: ^4.0.4
  image_picker: ^0.8.4+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/Image.png
    - lib/assets/images/image2.png

